// Generated by CoffeeScript 1.3.3

({
  name: "main",
  out: "../built-js/main.js",
  paths: {
    underscore: "libs/underscore",
    backbone: "libs/backbone"
  },
  optimize: "uglify",
  shim: {
    underscore: {
      exports: "_"
    },
    backbone: {
      deps: ["underscore"],
      exports: "Backbone"
    }
  }
});
