// Generated by CoffeeScript 1.3.3
/*global require
*/

require.config({
  paths: {
    underscore: 'libs/underscore',
    backbone: 'libs/backbone',
    bootstrap: 'libs/bootstrap'
  },
  shim: {
    underscore: {
      exports: '_'
    },
    backbone: {
      deps: ['underscore'],
      exports: 'Backbone'
    }
  }
});

require(['underscore', 'backbone', 'Models/User', 'Views/Main', 'Views/Login', 'Views/UserDetails', 'Router'], function(_, Backbone, UserModel, MainView, LoginView, UserDetailsView) {
  'use strict';

  var loginView, mainView, userDetailsView, userModel;
  userModel = new UserModel();
  mainView = new MainView({
    model: userModel
  });
  loginView = new LoginView({
    model: userModel
  });
  userDetailsView = new UserDetailsView({
    model: userModel
  });
});
