// Generated by CoffeeScript 1.3.3
/*global define
*/

define(['underscore', 'backbone'], function(_, Backbone) {
  'use strict';
  return Backbone.Router.extend({
    routes: {
      'queries': 'queries',
      'tickets': 'tickets',
      'tickets/query/:queryId': 'tickets',
      'dates': 'dates',
      'chart/tickets/:tickets/from/:from/to/:to': 'chart',
      '*actions': 'queries'
    },
    queries: function() {
      return window.console.log('queries');
    }
  });
});
