// Generated by CoffeeScript 1.3.3
/*global define
*/

define(['underscore', 'backbone', 'text!Templates/Chart.html'], function(_, Backbone, chartTemplate) {
  'use strict';
  return Backbone.View.extend({
    el: '#chart',
    initialize: function() {
      return this.render();
    },
    template: _.template(chartTemplate, {}),
    render: function() {
      this.$el.html(this.template);
    }
  });
});
