// Generated by CoffeeScript 1.3.3
/*global define
*/

define(['underscore', 'backbone', 'text!Templates/Dates.html'], function(_, Backbone, datesView) {
  'use strict';
  return Backbone.View.extend({
    el: '#dates',
    initialize: function() {
      return this.render();
    },
    template: _.template(datesView, {}),
    render: function() {
      this.$el.html(this.template);
    }
  });
});
