// Generated by CoffeeScript 1.3.3
/*global define
*/

define(['underscore', 'backbone', 'text!Templates/Main.html', 'Views/Queries', 'Views/Tickets', 'Views/Dates', 'Views/Chart'], function(_, Backbone, mainTemplate, QueriesView, TicketsView, DatesView, ChartView) {
  'use strict';
  return Backbone.View.extend({
    el: '#main',
    initialize: function() {
      this.model.on('change', this.render, this);
      return this.render();
    },
    template: _.template(mainTemplate, {}),
    render: function() {
      if (this.model.get('isLoggedIn')) {
        this.$el.html(this.template);
        this.queries = new QueriesView();
        this.tickets = new TicketsView();
        this.dates = new DatesView();
        this.chart = new ChartView();
      }
    }
  });
});
