// Generated by CoffeeScript 1.3.3
/*global define
*/

define(['underscore', 'backbone', 'text!Templates/UserDetails.html', 'bootstrap'], function(_, Backbone, userDetailsTemplate) {
  'use strict';
  return Backbone.View.extend({
    el: '#userDetails',
    initialize: function() {
      this.model.on('change', this.render, this);
      return this.render();
    },
    events: {
      'click .btnLogOut': 'logOut'
    },
    template: _.template(userDetailsTemplate),
    render: function() {
      if (this.model.get('isLoggedIn')) {
        this.$el.html(this.template(this.model.toJSON()));
      } else {
        this.$el.html('');
      }
    },
    logOut: function() {
      return this.model.logOut();
    }
  });
});
