// Generated by CoffeeScript 1.3.3
/*global define
*/

define(['underscore', 'backbone'], function(_, Backbone) {
  'use strict';
  return Backbone.Model.extend({
    defaults: {
      'apiKey': '',
      'username': '',
      'isLoggedIn': false
    },
    initialize: function() {
      var result;
      if (window.localStorage) {
        result = window.localStorage.getItem('apiKey');
        if (result != null) {
          return this.logIn(result, function() {});
        }
      }
    },
    logIn: function(key, error) {
      var _this = this;
      return $.ajax('User.json?' + key, {
        dataType: 'json',
        success: function(data) {
          _this.set({
            'apiKey': key
          });
          _this.set({
            'username': data.userName
          });
          _this.set({
            'isLoggedIn': true
          });
          if (window.localStorage) {
            return window.localStorage.setItem('apiKey', key);
          }
        },
        error: error
      });
    },
    logOut: function() {
      this.set({
        'apiKey': ''
      });
      this.set({
        'username': ''
      });
      this.set({
        'isLoggedIn': false
      });
      if (window.localStorage) {
        return window.localStorage.removeItem('apiKey');
      }
    }
  });
});
